---
title: "Donnees Quotidiennes Des Cas de COVID 19 Au Senegal"   
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
    theme: bootstrap
---

```{r setup, include=FALSE}
# options(scipen = 12)
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      comment = NA,
                      error   = FALSE,
                      warning = FALSE,
                      cache = FALSE)

source("R/sencovid19.R")

decedes <- last(sencovid_cumule$total_decedes) 
gueris <- last(sencovid_cumule$total_gueris) 
total <- last(sencovid_cumule$total_confirmes)
library(knitr)
library(rmarkdown)
library(flexdashboard)
library(shiny)
library(tsibble)
library(tidycovid19)

```


Sommaire
=====================================

</br>

  Les donnees proviennent principalement des communiques officiels du ministere de la sante du gouvernement du Senegal. 
  Les dernieres donnees sont en date du __`r last_date `__
  
</br>


 
    
Row
-------------------------------------   



### Gueris  
    
```{r}
valueBox(value = gueris,
         icon = "fa-thumbs-up",
         color = "#35B779FF")
 

```

### Confirmes  
    
```{r}
flexdashboard::valueBox(value = total,
                        icon = "fa-area-chart",
                        color =  "#FDE725FF")
 

```


### Decedes  

```{r}
valueBox(value = decedes,
         icon = "fa-heartbeat",
         color = "#F1605DFF")

```

</br>


Epicurves
=====================================


Row
------------------------------------- 

### Epicurve - Incidence 


```{r epicurvec, layout="l-body-outset", fig.width= 8, fig.height= 6.5, fig.cap=''}

sen_epic2

  

```

</br>

Row
-------------------------------------   

### Epicurve - Cumulative


```{r epi_cc, layout="l-body-outset", fig.width= 8, fig.height= 6.5, fig.cap=''}

cum_epi

```

</br>

Comparison Mondiale
=====================================   

</br>

Row
-------------------------------------   

### Senegal compare Au Reste du Monde Depuis Le 100eme Cas

```{r world, layout="l-body-outset", fig.width= 8, fig.height= 6.5, fig.cap=''}
# 
# Download latest data
updates <- download_merged_data(cached = TRUE)
# Countries to highlight
countries <- c("SEN", "ZAF","MAR","FRA", "ITA", "ESP", "USA", "CHN")
w_plot <- updates %>%
  plot_covid19_spread(
    highlight = countries,
    type = "confirmed",
    edate_cutoff = 40
  )

ggplotly(w_plot)

```


</br>

Sources
=====================================   

</br>

Row
-------------------------------------   

### Communiques Quotidiens  

[Communiques Quotidiens Du Ministere De La Sante Du Senegal](http://www.sante.gouv.sn/Pr%C3%A9sentation/coronavirus-informations-officielles-et-quotidiennes-du-msas){target="_blank"}

</br>

Voir aussi la page [GitHub](https://github.com/epinotes/sencovid19) pour les codes R.

</br>

Row
-------------------------------------   

### Tableau Des Cas Confirmes Par Jour


```{r daily} 
covid19_daily %>% 
         DT::datatable(caption = "Nombre de Cas Confirmes par Date",

                rownames = FALSE,

                extensions = 'Buttons',

              filter = list(position = 'top', clear = FALSE),

              options = list(

                  pageLength = 10, dom = 'Bfrtip',

    buttons = c('copy', 'csv'),

    columnDefs = list(list(className = 'dt-left', targets = 1))

  ))
```

